### ISSUE TITLE
Upgrading to 0.30.0 causes error in Lucky::Subdomain settings

### ISSUE THREAD

**Issue by wout** [luckyframework/lucky#1685]
**Describe the bug**
After upgrading from 0.29.0 to 0.30.0 I'm getting the following error:

```
In lib/lucky/src/lucky/protect_from_forgery.cr:25:18

 25 | if !settings.allow_forgery_protection? || request_does_not_require_protection? || valid_csrf_token?
                   ^------------------------
Error: undefined method 'allow_forgery_protection?' for Lucky::Subdomain::HabitatSettings.class

Lucky::Subdomain::HabitatSettings.class trace:

  lib/lucky/src/lucky/protect_from_forgery.cr:25

        if !settings.allow_forgery_protection? || request_does_not_require_protection? || valid_csrf_token?
            ^~~~~~~~

  macro create (in /home/wout/Code/crystal/zow-v6/lib/habitat/src/habitat.cr:158):19

        def settings
            ^~~~~~~~

  macro create (in /home/wout/Code/crystal/zow-v6/lib/habitat/src/habitat.cr:158):20

          HabitatSettings
```

**Versions (please complete the following information):**
 - Lucky version (check in shard.lock): 0.30.0
 - Crystal version (`crystal --version`): 1.3.2
 - OS: elementary OS 6.1 (based on Ubuntu 20.04)

**Additional context**
Adding setting `allow_forgery_protection : Bool = true` to the habitat settings of `Lucky::Subdomain` fixes the issue.
